### ISSUE TITLE
auto indent of  HTMLish tags broken

### ISSUE THREAD

**Issue by amit777** [leafOfTree/vim-svelte-plugin#13]
Hi, here are the screenshots of the before and after auto indent (highlight all and hit `=`).   I've also included the raw tags if it's helpful below.

![Screen Shot 2021-03-30 at 11 07 28 PM](https://user-images.githubusercontent.com/2703309/113098084-da6e5b80-91ac-11eb-860b-c6e2bdc73c1d.png)

Notice the closing DIV and PAGE tags idents are messed up and not highlighted

![Screen Shot 2021-03-30 at 11 08 20 PM](https://user-images.githubusercontent.com/2703309/113098092-dcd0b580-91ac-11eb-8f17-dfcb14a3ac47.png)

Here is the raw code:
```svelte
<Page name="home" bgColor="gray">
  <div bind:this={panelEl}>
    <Row class="justify-content-center">
      <Col width="100" medium="30">
        <form on:submit={handleSubmit}>
          <Card>
            {#if checking}<Progressbar slot="root-start" infinite />{/if}
            <CardHeader class="justify-content-center" textColor="gray">
              <LoginScreenTitle>
                <OsLogo />
                <br /> Sign In
              </LoginScreenTitle>
            </CardHeader>

            <CardContent>
              <List inset>
                <ListInput
                  errorMessageForce={formErrors.email}
                  errorMessage={formErrors.email}
                  floatingLabel="true"
                  input={false}
                  label="Work Email"
                  type="email"
                  clearButton
                  outline
                >
                  <input slot="input" type="text" id="email" name="email" on:change={handleChange} bind:value={$form.email} />
                </ListInput>
              </List>
            </CardContent>
            <CardFooter class="justify-content-center">
              <Block style="width:100%">
                <Row>
                  <Col>
                    <Button on:click={() => f7router.navigate('/register/')} tabindex="1" href="/register/" ignoreCache={true}>Register</Button>
                  </Col>
                  <Col>
                    <Button tabindex="0" type="submit" fill raised>Next</Button>
                  </Col>
                </Row>
              </Block>
            </CardFooter>
          </Card>
        </form>
        <SsoList />
      </Col>
    </Row>
  </div>
</Page>
```

**Comment by amit777** [comment]
I was wondering, is it possible to simplify the syntax highlight/auto-indentation by using the svelte prettier plugin?  I'm a vim newb, so not sure if that even makes sense.

**Comment by leafOfTree** [comment]
Hi, the screenshots and raw code are very helpful. I noticed the indent was broken after `<Col>`. That's because `<col>` is treated specially as an empty tag and I didn't take care of the case before. Now it should be fixed.

In my experience, prettier is an external tool that reads a file then outputs a formatted one. On the other hand, Vim handles every line's syntax/indent by inner commands written with its own language VimScript. Though vim can call any external tool, it doesn't look straightforward and efficient in this case.

**Comment by amit777** [comment]
Awesome, I just tested it out and it looks a lot better.  However, there still seems to be an issue where the closing tags are now too indented.  It seems related to the `{#if}` syntax.  Here is the new screenshot. 

![Screen Shot 2021-03-31 at 10 02 24 PM](https://user-images.githubusercontent.com/2703309/113245944-d6097780-926c-11eb-9d5d-f5e36ebe21c2.png)

**Comment by amit777** [comment]
If I put the `<Progressbar slot="root-start infinite />` on its own line, the indentation seems to be fixed

**Comment by leafOfTree** [comment]
Exactly the same issue I just found when `{#if}...{/if}` appears on one line. I just fixed it as well. Please check it out.

**Comment by amit777** [comment]
awesome, looks fixed for me as well!  thank you!!!

**Comment by amit777** [comment]
I'm adding a note to the vim-polyglot project to ask them to include your plugin rather than the one they are currently using for svelte.

**Comment by amit777** [comment]
https://github.com/sheerun/vim-polyglot/issues/700  if you want to give it a thumbs up

**Comment by leafOfTree** [comment]
Hey, thanks a lot for your recognition.

**Comment by leafOfTree** [comment]
I'm closing it. Feel free to reopen it if you have any questions.
