### ISSUE TITLE
Typescript syntax highlighting with typescript-vim

### ISSUE THREAD

**Issue by wilitp** [leafOfTree/vim-svelte-plugin#14]
Setting `lang` to either `ts` or `typescript` makes the text between `<script>` tags be shown without any highlighting.

I have installed `typescript-vim` and it's working correctly as it seems. 

You can find my full .vimrc file [here](https://github.com/wilitp/.dotfiles/blob/master/.vimrc)

**Comment by leafOfTree** [comment]
Hi, you probably forget to add config in .vimrc to enable typescript
```vim
let g:vim_svelte_plugin_use_typescript = 1
```
Then setting lang to `ts` should work.

**Comment by wilitp** [comment]
Thanks! I somehow missed that part in the settings table.

**Comment by leafOfTree** [comment]
No problem
