### ISSUE TITLE
Indentation Issue

### ISSUE THREAD

**Issue by mo-shaz** [leafOfTree/vim-svelte-plugin#16]
Sorry if this is already in the docs and I missed it, my vim setting for indentation using tab is 4 chars but inside svelte files and TypeScript files inside my svelte directory it uses 8 chars. Is there a config I'm missing? Thanks in advance, this is a great plugin :D.

**Comment by leafOfTree** [comment]
Thank you for the compliment :). 
You can specify the indentation for svelte files in your vim setting as below
```vim
autocmd FileType svelte setlocal shiftwidth=4
```

**Comment by mo-shaz** [comment]
> Thank you for the compliment :). You can specify the indentation for svelte files in your vim setting as below
> 
> ```viml
> autocmd FileType svelte setlocal shiftwidth=4
> ```

Thank you so much. It works now. I'm new to vim and learning the basic config and settings, thanks for helping me out :D.
