### ISSUE TITLE
Inline arrow functions on svelte elements cause issues

### ISSUE THREAD

**Issue by Arro** [leafOfTree/vim-svelte-plugin#17]
Hello,

See the screenshot here:

![Screen Shot 2022-02-18 at 7 49 43 AM](https://user-images.githubusercontent.com/180387/154686115-3ccdb6a4-c7ed-4bac-a88d-15d7d6e5f098.png)

Note how it breaks highlighting on the arrow style, but not on the traditional style.

I'm curious if anyone else has this.  Interestingly, I have the exact same issue when switching to [this similar plugin](https://github.com/evanleck/vim-svelte), so it may be something weird with my `.vimrc`.  Or maybe both plugins import the same library.

**Comment by leafOfTree** [comment]
Hi, @Arro Thanks for the feedback. It indeed is a syntax highlight error of this plugin.
I managed to fix it and it should look like follow after updating this plugin
<img width="296" alt="Screen Shot 2022-02-21 at 3 16 44 PM" src="https://user-images.githubusercontent.com/13349592/154906685-ec0b0efb-c208-4cd4-a400-4c4601152fc5.png">

However, currently, the syntax highlight for inline JavaScript expressions is not quite perfect yet. It requires a trailing `}}` to recognize an inline function on svelte elements.

**Comment by Arro** [comment]
Thank you for fixing this!  Confirmed working now on my end.
