### ISSUE TITLE
Broken indentation inside <style> tag

### ISSUE THREAD

**Issue by gbenson-ff** [leafOfTree/vim-svelte-plugin#19]
When using this plugin, indentation doesn't work correctly inside the `<style>` tag of my `.svelte` files.

After hitting enter, the cursor will be back at the start rather than following the indentation pattern.  If there are indented lines above/below the cursor, they will also lose their indentation.

I have `let g:vim_svelte_plugin_has_init_indent = 1` in my `.vimrc`, but changing it to `0` doesn't affect the behavior.

See this recording for an example:
![screencast](https://user-images.githubusercontent.com/67277054/163728991-84dba60b-1339-4b0f-a2c2-6efb4d527c34.gif)

If there's any other information I can provide to help, please let me know!  The plugin works perfectly other than this one issue!

**Comment by leafOfTree** [comment]
Hi there,
Thanks for your feedback. Not sure why it doesn't work for you.

To help narrow down the problem scope, can you please try the below steps for the `.svelte` file?

- `:let g:vim_svelte_plugin_debug = 1`
- `:set debug=msg`
- visual select code inside `<style>` tag and press `=` to indent them
- check the logs and errors, if any, by `:messages`.
---
In case the previous one doesn't produce an interesting result, there are other directions you may check if you like. 
- Is there any other plugin that may impact the indentation, such as a formatter? 
- Does indentation work on normal `.scss` files?
- Did you remap `<enter>` to call something to expand `{}` that may change the indentation?

**Comment by gbenson-ff** [comment]
@leafOfTree Sorry for taking a while to reply.  I haven't tried the above yet, but will soon.

I'll get set up in a vanilla env to make sure no conflicting plugins are interfering.

**Comment by gbenson-ff** [comment]
@leafOfTree So, I set up a clean vim (technically neovim) env with only `vim-svelte-plugin`, `vim-pug`, and `yats.vim` installed and did not have the indentation issue.

I swapped those 3 plugins for `vim-polyglot` (what I use in my main env) and then was able to reproduce the issue.  So, maybe it's an issue on their end and not on yours?

Regardless, I went through the steps you mentioned in my main (not clean) env, and this was the result:

```sh
8 lines to indent...                                                                                                        
Error detected while processing function GetSvelteIndent:                                                                   
line   56:                                                                                                                  
E117: Unknown function: GetCSSIndent
```

For your other question, yes indentation works with normal `.scss` files, and no I haven't remapped `<enter>` unless another plugin was doing it.

For further reference, this is the minimal `.vimrc` config that presented me with the issue:

```
call plug#begin()
  Plug 'sheerun/vim-polyglot'
call plug#end()

" Svelte
" let g:vim_svelte_plugin_load_full_syntax = 1
let g:vim_svelte_plugin_use_pug = 1
let g:vim_svelte_plugin_use_typescript = 1
let g:vim_svelte_plugin_use_sass = 1
let g:vim_svelte_plugin_has_init_indent = 1
```

If you think it's safe to say that this is likely an issue with `vim-polyglot`, just say the word and I'll close this issue out and take it up with them.  Just wanted to run this by you first.  Thanks for your help!

**Comment by leafOfTree** [comment]
Hi there, 
Thanks for your time for testing. That is very helpful! 

It turns out that it was because I put `css.vim` and `xml.vim` indent files in another folder `lib`, and `vim-polyglot` didn't load them together with `svelte.vim`. 
As a solution, I moved both files to `indent` folder (now `svelte-css.vim`,`svelte-xml.vim`, and `svelte.vim`). I've submitted the changes https://github.com/leafOfTree/vim-svelte-plugin/commit/81fdbd57f5e60c2654249c1bbc3072720eeaa27f. 

According to https://github.com/sheerun/vim-polyglot#updating, and the uncertainty of when `vim-polyglot` will update, you may try one of below

- run `make` inside local `vim-polyglot`
- or copy all files in `vim-svelte-plugin/indent` to local `vim-polyglot/indent`
- or wait for remote `vim-polyglot` to update

In case of any doubt, feel free to let me know.

**Comment by gbenson-ff** [comment]
Awesome, that fixed it!  Thanks so much!
