### ISSUE TITLE
In svelte's code blocks, the "%" key does not work.

### ISSUE THREAD

**Issue by roket1428** [leafOfTree/vim-svelte-plugin#2]
As in if blocks.
```
{#if <my condition>}
  ...
{/if}
```

**Comment by leafOfTree** [comment]
As `:h %` shows
> 			#if, #ifdef, #else, #elif, #endif
>					C preprocessor conditionals (when the
>					cursor is on the # or no ([{
>					following)

The source code: https://github.com/vim/vim/blob/8e95636a282f3eac808c0e00c053b33334cc283e/runtime/pack/dist/opt/matchit/autoload/matchit.vim#L80
It's written as a constant string. So when the cursor is on the `#if` of `{#if expression}`, it won't work.

**Comment by roket1428** [comment]
> As `:h %` shows
> 
> > ```
> >   	#if, #ifdef, #else, #elif, #endif
> >   			C preprocessor conditionals (when the
> >   			cursor is on the # or no ([{
> >   			following)
> > ```
> 
> The source code: https://github.com/vim/vim/blob/8e95636a282f3eac808c0e00c053b33334cc283e/runtime/pack/dist/opt/matchit/autoload/matchit.vim#L80
> It's written as a constant string. So when the cursor is on the `#if` of `{#if expression}`, it won't work.

Works perfectly, thanks.
