### ISSUE TITLE
Typescript features within script

### ISSUE THREAD

**Issue by acurrieclark** [leafOfTree/vim-svelte-plugin#21]
This might be outside the scope of this package, but I am just getting used to the setup of NeoVim and am trying to understand how everything integrates.

I have a few typescript code actions set up which work just fine in `.ts` files, but I noticed today that they don't work in svelte typescript block. Do you know if there is a way to set that up?

I thought perhaps I could find a way to set the context using the `GetSvelteTag()` etc functions? But I couldn't work out how to invoke them using lua. 

I do have `vim.g.vim_svelte_plugin_use_typescript = 1` in my config.

Any advice would be gratefully received, but please let me know if this is outside scope and I will explore elsewhere.

**Comment by leafOfTree** [comment]
Sorry for the late reply.

Honestly, I've not used much Lua in Neovim. I suppose you want to reuse typescript code actions written in Lua for Svelte.

After doing some research. I think you can invoke vim functions using lua `vim.fn` like below
```
:lua print(vim.fn.GetSvelteTag())
:lua print(vim.fn.GetSvelteSubtype())
```

to check if the functions' return values are `script` and `typescript`.

**Comment by acurrieclark** [comment]
Thanks for the feedback, i'll give both a try.

Will close for now.
