### ISSUE TITLE
Sass Syntax Highlighting

### ISSUE THREAD

**Issue by kolchurinvv** [leafOfTree/vim-svelte-plugin#22]
Hey!
I'm pretty sure it's a skill issue on my part, but I cannot for the life of me figure out how to enable syntax highlighting in `.svelte` files in `<style lang="sass">` tags. screenshot of how it looks:
![Screenshot 2023-11-07 at 20 12 36](https://github.com/leafOfTree/vim-svelte-plugin/assets/18503099/dd2884a6-722a-443d-af97-0aebd31a89c5)
path for this: `~/.config/nvim/lua/custom/plugins/init.lua`
![Screenshot 2023-11-07 at 20 13 19](https://github.com/leafOfTree/vim-svelte-plugin/assets/18503099/ba57095d-e4bc-4f8b-b8cc-65735bba7819)

the plugins are loaded in in init.lua like so:
```lua
require('lazy').setup({
{...},
{ import = 'custom.plugins' },
},{})
```

`:echo g:vim_svelte_plugin_use_sass` returns 1
`:echo &filetype` returns svelte

Please help! Thanks!

**Comment by leafOfTree** [comment]
Hey, there
You can try to wrap the first plugin `auto-dark-mode.nvim` and its config in`{...}`. Below works for me.
```lua
return {
  {
    "f-person/auto-dark-mode.nvim", 
    config = {
      update_interval = 500, 
      set_dark_mode = function ()
        vim.cmd("colorscheme onedark")
      end, 
      set_light_mode = function ()
        vim.api.nvim_set_option("background", "light")
        vim.cmd("colorscheme gruvbox")
      end, 
    }, 
  }, 
  {
    "leafoftree/vim-svelte-plugin", 
    config = function ()
      vim.g.vim_svelte_plugin_use_sass = 1
    end
  }, 
  {
    "morhetz/gruvbox", 
  }, 
  {
    "joshdick/onedark.vim", 
  }, 
}
```
<img width="248" alt="Screen Shot 2023-11-23 at 14 05 10" src="https://github.com/leafOfTree/vim-svelte-plugin/assets/13349592/c2055e3d-e008-4016-8c3c-3aeb87e705c5">

**Comment by kolchurinvv** [comment]
Sorry it took me a while to respond - my nvim skills are still in its infancy, so i'm only using it sparsely.

Took me a while to get it through my head, but i've got it! My issue is that treesitter is overtaking this plugin in its highlighting duties. when i comment out line 323 - everything works just as advertised 😄
```lua
...
W 316 require('nvim-treesitter.configs').setup {
  317 ▎ -- Add languages to be installed here that you want installed for treesitter
  318 ▎ ensure_installed = { 'c', 'cpp', 'go', 'lua', 'python', 'rust', 'tsx', 'typescript', 'vimdoc', 'vim' },
  319 ▎
  320 ▎ -- Autoinstall languages that are not installed. Defaults to false (but you can change for yourself!)
  321 ▎ auto_install = true,
  322 ▎
  323 ▎ highlight = { enable = true }
  ...
```

would you be so kind and land a hand with setting up treesitter to play nice?

chatgpt4 suggests adding this to my config:
```lua
vim.cmd [[
augroup SvelteTreesitterOverride
  autocmd!
  autocmd FileType svelte :lua require'nvim-treesitter.configs'.highlight.disable()
augroup END
]]
```
would you say that makes sense? is there another way?

**Comment by kolchurinvv** [comment]
actually, after a little more digging this is what i ended up with:
```lua
highlight = {
 enable = true,
 disable = function(lang, bufnr)
   return vim.bo[bufnr].filetype == 'svelte'
 end,
}
```

**Comment by kolchurinvv** [comment]
clearly a skill issue on my end 🤪 
in any case, if you could let me know of a correct way to configure treesitter + vim-svelte-plugin -- i would really appreciate it!

**Comment by leafOfTree** [comment]
unfortunately, i'm unfamiliar with treesitter, neither
 i'm trying nvim recently. will let you know if i find anything
