### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by dvlpr91** [leafOfTree/vim-svelte-plugin#23]
Syntax highlighting does not work when using arrow function expressions.

`<svelte:window on:keydown={(e) => console.log(e)} />`

**Comment by leafOfTree** [comment]
Hi there. 

I fixed it for Typescript syntax. Please update and check.

<img width="496" alt="image" src="https://github.com/leafOfTree/vim-svelte-plugin/assets/13349592/eeaa935e-5c00-451f-9d35-1273e9634cf2">


 If it doesn't fix your case, please let me know what script syntax and relevant plugins you're using.

**Comment by dvlpr91** [comment]
I have already left vim and moved on to vscode.

I trust you would have done fine.

I apologize for not being able to check the results.
