### ISSUE TITLE
Unhighlighted directives.

### ISSUE THREAD

**Issue by roket1428** [leafOfTree/vim-svelte-plugin#3]
In there, "in:, out: transition:" directives and their right hand side thingies are not highlighted.
```html
<script>
	import { fade, fly } from 'velte/transition';
	let visible = true;
</script>

<label>
	<input type="checkbox" bind:checked={visible}>
	visible
</label>

{#if visible}
	<p in:fly={{ y: 200, duration: 2000 }} out:fade>
		Flies in, fades out
	</p>

	<p transition:fade>
		Fades in, fades out.
	</p>
{/if}
```

**Comment by leafOfTree** [comment]
Hi, thank you for the feedback. I've added `in, out, transition`. Now they should be highlighted.

**Comment by roket1428** [comment]
> Hi, thank you for the feedback. I've added `in, out, transition`. Now they should be highlighted.

Thanks a lot.
