### ISSUE TITLE
closing tag is not included in the fold?

### ISSUE THREAD

**Issue by chiefjester** [leafOfTree/vim-svelte-plugin#5]
Hi 👋🏻, Thanks for making this! I was checking the fold expression and tried it out in `Svelte` sample file. The closing tag for HTML seems to be not included in the fold? Is that intentional? If so is there an option to add the closing tag inside the fold?

![image](https://user-images.githubusercontent.com/532797/65514056-174df800-df0f-11e9-8881-f92a2d2a6ecd.png)

**Comment by chiefjester** [comment]
Also another question, do you still need the first line here, if I have the 2nd line enabled?

```
let g:vim_svelte_plugin_use_foldexpr = 1
let g:vim_svelte_plugin_load_full_syntax = 1
```

**Comment by leafOfTree** [comment]
Hi, thanks for the feedback. It's a bug to fix that I didn't notice before. The closing tag should be included.

The first line is still needed to enable `foldexpr` foldmethod if the 2nd line is enabled.

**Comment by leafOfTree** [comment]
It should create folds properly for html closing tags now.

**Comment by leafOfTree** [comment]
I am closing this issue. Feel free to reopen it if there is still any problem.
