### ISSUE TITLE
Plugin doesn't works if using vim-vue-plugin.

### ISSUE THREAD

**Issue by DiegoFHG** [leafOfTree/vim-svelte-plugin#7]
Seems that this plugin doesn't work if I have installed your other plugin `vim-vue-plugin`. But if I removed it, it starts working. No error messages, nothing. So the only work around for now is to remove the vue plugin everytime I want to work on a svelte app.

**Comment by leafOfTree** [comment]
Hi, thank you for reporting this issue. I need more information to find out. Could you please provide something like
- Vim version
- How do you install the two plugins

**Comment by DiegoFHG** [comment]
I use NeoVim 0.4.3, I install plugins with dein:

```
call dein#add('leafOfTree/vim-svelte-plugin')                                                                                                   
call dein#add('leafOfTree/vim-vue-plugin')
```

Then I run `call dein#install()` and `dein#recache_runtimepath()`

I use CoC with coc-svelte, I don't know if it is relevant.

**Comment by leafOfTree** [comment]
Thanks for the information. It helps me to find out that `dein` only keeps one `filetype.vim`. So I moved it to `ftdetect` for both plugins. 

It should work after reinstalling them.

**Comment by DiegoFHG** [comment]
Yeah, now it works like a charm. Thanks.
