### ISSUE TITLE
Tags with line breaks lose highlight

### ISSUE THREAD

**Issue by rxw1** [leafOfTree/vim-svelte-plugin#8]
Hi!

![image](https://user-images.githubusercontent.com/154026/96143276-3b59ee00-0f03-11eb-9fc4-09df9dd8bf14.png)

This seems to happen only on top level. Anything nested displays correctly.

![image](https://user-images.githubusercontent.com/154026/96146087-39455e80-0f06-11eb-819a-71a612a5d8c6.png)

**Comment by kaishiro** [comment]
Came to report the same issue. Everything else working as intended.

**Comment by leafOfTree** [comment]
Hi, thank you for reporting this omission. I've added a syntax group for top-level empty tags.
<img width="247" alt="Screen Shot 2020-10-19 at 2 20 29 PM" src="https://user-images.githubusercontent.com/13349592/96408514-415b1200-1216-11eb-9ec3-32eb7dffdf4f.png">

**Comment by rxw1** [comment]
Thank you!
