### ISSUE TITLE
Incorrect html closing tag syntax highlighting when opening tag spans multiple lines

### ISSUE THREAD

**Issue by caschbre** [leafOfTree/vim-svelte-plugin#9]
![image](https://user-images.githubusercontent.com/326357/96918696-ec163f00-1467-11eb-8b52-a29c2fbc245a.png)

If you look at the attached screenshot, you'll notice the closing </div> tag in the 2nd example lost syntax highlighting.  It seems to do that when the opening tag spans multiple lines.

**Comment by caschbre** [comment]
![image](https://user-images.githubusercontent.com/326357/96918960-49aa8b80-1468-11eb-996b-a1e4ccbad91b.png)

So that's not entirely accurate. Here's an updated screenshot with a 3rd example so you can see the differences. It looks like the usage of <slot/> vs <slot></slot> comes in to play.

**Comment by leafOfTree** [comment]
Hi, thank you for the feedback. I've adjusted the syntax pattern to highlight tags span multiple lines correctly. Please update the plugin and see if it works for you.

<img width="391" alt="Screen Shot 2020-10-23 at 2 17 54 PM" src="https://user-images.githubusercontent.com/13349592/96963053-8d6dc580-153a-11eb-87ce-2dd839334c01.png">

**Comment by caschbre** [comment]
I just tested the update and it did appear to fix those issues.  Thanks!

Not sure if this is related (I can create a separate issue if needed) but when testing the update, I noticed the following syntax highlighting issue.

![image](https://user-images.githubusercontent.com/326357/97047776-b5f3c080-1536-11eb-9fa6-9b5b817a4941.png)

Looks like it doesn't like "Page" being used. Both PageSize and Pager changed color after "Page".

**Comment by leafOfTree** [comment]
Thank you for finding the "Page" issue. I don't remember very well, but it seems to be related to `svelte-native` support. 
Since it causes the highlighting issue. I've removed the syntax group. The "Page.*" syntax should be fixed after this update.

**Comment by caschbre** [comment]
Awesome! The update looks great. Thanks for the quick turn-around!!

**Comment by leafOfTree** [comment]
Great. I'm happy to hear that.
